name: Deploy docker image from ghcr to server

on: workflow_dispatch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}:latest

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Connect server and deploy new image to docker compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            export CR_PAT=${{ secrets.PAT }}
            echo $CR_PAT | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin
            cd api
            docker compose pull api
            docker compose up api --force-recreate -d
